2025-01-05 16:54:14,151 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-05 16:54:14,151 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Configure stats pid to 44476
2025-01-05 16:54:14,151 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2025-01-05 16:54:14,151 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from c:\xampp\htdocs\Smoker_Detection\wandb\settings
2025-01-05 16:54:14,151 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-05 16:54:14,151 INFO    MainThread:44476 [wandb_init.py:_log_setup():528] Logging user logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_165414-wo0awy8j\logs\debug.log
2025-01-05 16:54:14,152 INFO    MainThread:44476 [wandb_init.py:_log_setup():529] Logging internal logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_165414-wo0awy8j\logs\debug-internal.log
2025-01-05 16:54:14,152 INFO    MainThread:44476 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001CEB6902ED0>
2025-01-05 16:54:14,152 INFO    MainThread:44476 [wandb_init.py:init():644] calling init triggers
2025-01-05 16:54:14,152 INFO    MainThread:44476 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32, 'img_height': 250, 'img_width': 250}
2025-01-05 16:54:14,152 INFO    MainThread:44476 [wandb_init.py:init():680] starting backend
2025-01-05 16:54:14,152 INFO    MainThread:44476 [wandb_init.py:init():684] sending inform_init request
2025-01-05 16:54:14,206 INFO    MainThread:44476 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-05 16:54:14,206 INFO    MainThread:44476 [wandb_init.py:init():697] backend started and connected
2025-01-05 16:54:14,208 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1222] probe notebook
2025-01-05 16:54:14,210 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1232] Unable to probe notebook: 'gbk' codec can't decode byte 0x80 in position 46717: illegal multibyte sequence
2025-01-05 16:54:14,210 INFO    MainThread:44476 [wandb_init.py:init():790] updated telemetry
2025-01-05 16:54:14,259 INFO    MainThread:44476 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-05 16:54:14,714 ERROR   MainThread:44476 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-05 16:54:14,714 ERROR   MainThread:44476 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-05 16:59:37,087 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Configure stats pid to 44476
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from c:\xampp\htdocs\Smoker_Detection\wandb\settings
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_init.py:_log_setup():528] Logging user logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_165937-9o8sgchq\logs\debug.log
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_init.py:_log_setup():529] Logging internal logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_165937-9o8sgchq\logs\debug-internal.log
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_init.py:init():644] calling init triggers
2025-01-05 16:59:37,088 INFO    MainThread:44476 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32, 'img_height': 250, 'img_width': 250}
2025-01-05 16:59:37,089 INFO    MainThread:44476 [wandb_init.py:init():680] starting backend
2025-01-05 16:59:37,089 INFO    MainThread:44476 [wandb_init.py:init():684] sending inform_init request
2025-01-05 16:59:37,092 INFO    MainThread:44476 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-05 16:59:37,092 INFO    MainThread:44476 [wandb_init.py:init():697] backend started and connected
2025-01-05 16:59:37,093 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1222] probe notebook
2025-01-05 16:59:37,095 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1232] Unable to probe notebook: 'gbk' codec can't decode byte 0x80 in position 54629: illegal multibyte sequence
2025-01-05 16:59:37,096 INFO    MainThread:44476 [wandb_init.py:init():790] updated telemetry
2025-01-05 16:59:37,148 INFO    MainThread:44476 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-05 16:59:37,509 ERROR   MainThread:44476 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-05 16:59:37,509 ERROR   MainThread:44476 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Configure stats pid to 44476
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from c:\xampp\htdocs\Smoker_Detection\wandb\settings
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_init.py:_log_setup():528] Logging user logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_170024-qcg8g8au\logs\debug.log
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_init.py:_log_setup():529] Logging internal logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_170024-qcg8g8au\logs\debug-internal.log
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_init.py:init():644] calling init triggers
2025-01-05 17:00:24,662 INFO    MainThread:44476 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32, 'img_height': 250, 'img_width': 250}
2025-01-05 17:00:24,663 INFO    MainThread:44476 [wandb_init.py:init():680] starting backend
2025-01-05 17:00:24,663 INFO    MainThread:44476 [wandb_init.py:init():684] sending inform_init request
2025-01-05 17:00:24,667 INFO    MainThread:44476 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-05 17:00:24,667 INFO    MainThread:44476 [wandb_init.py:init():697] backend started and connected
2025-01-05 17:00:24,669 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1222] probe notebook
2025-01-05 17:00:24,670 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1232] Unable to probe notebook: 'gbk' codec can't decode byte 0x80 in position 54368: illegal multibyte sequence
2025-01-05 17:00:24,670 INFO    MainThread:44476 [wandb_init.py:init():790] updated telemetry
2025-01-05 17:00:24,720 INFO    MainThread:44476 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-05 17:01:55,387 ERROR   MainThread:44476 [wandb_init.py:init():849] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-05 17:01:55,387 ERROR   MainThread:44476 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-05 17:04:53,771 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-05 17:04:53,771 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Configure stats pid to 44476
2025-01-05 17:04:53,771 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2025-01-05 17:04:53,771 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from c:\xampp\htdocs\Smoker_Detection\wandb\settings
2025-01-05 17:04:53,771 INFO    MainThread:44476 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-05 17:04:53,771 INFO    MainThread:44476 [wandb_init.py:_log_setup():528] Logging user logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_170453-sd49vsgd\logs\debug.log
2025-01-05 17:04:53,772 INFO    MainThread:44476 [wandb_init.py:_log_setup():529] Logging internal logs to c:\xampp\htdocs\Smoker_Detection\wandb\run-20250105_170453-sd49vsgd\logs\debug-internal.log
2025-01-05 17:04:53,772 INFO    MainThread:44476 [wandb_init.py:init():644] calling init triggers
2025-01-05 17:04:53,772 INFO    MainThread:44476 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32, 'img_height': 250, 'img_width': 250}
2025-01-05 17:04:53,772 INFO    MainThread:44476 [wandb_init.py:init():680] starting backend
2025-01-05 17:04:53,772 INFO    MainThread:44476 [wandb_init.py:init():684] sending inform_init request
2025-01-05 17:04:53,776 INFO    MainThread:44476 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-05 17:04:53,777 INFO    MainThread:44476 [wandb_init.py:init():697] backend started and connected
2025-01-05 17:04:53,778 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1222] probe notebook
2025-01-05 17:04:53,781 INFO    MainThread:44476 [wandb_run.py:_label_probe_notebook():1232] Unable to probe notebook: 'gbk' codec can't decode byte 0x80 in position 54117: illegal multibyte sequence
2025-01-05 17:04:53,781 INFO    MainThread:44476 [wandb_init.py:init():790] updated telemetry
2025-01-05 17:04:53,832 INFO    MainThread:44476 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-05 17:04:54,183 ERROR   MainThread:44476 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-05 17:04:54,183 ERROR   MainThread:44476 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "c:\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
